services:
  adminer:
    networks:
      - katara
    image: adminer
    restart: always
    ports:
      - 8000:8000
  db:
    networks:
      - katara
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123

networks:
  katara:
    name: katara
    driver: bridge